
name: publish-workflow

on:
  push:
    tags:
      - v0.*

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PROJECT: ${{ secrets.DOCKER_PROJECT }}
    steps:
      - name: checks out a copy of your repository
        uses: actions/checkout@v2
      - name: retrieve tag ref and set image_version
        run: echo ::set-env name=IMAGE_VERSION::${GITHUB_REF:11}    
      - name: update ubuntu and install make tool
        run: |
          sudo apt-get update -y
          sudo apt-get install -y make
      - name: download trivy and install trivy tool
        run: |
          TRIVY_VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/') ;
          curl -sfLo - https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz | sudo tar xz -C /usr/bin trivy || true
      - name: docker registry authentication
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin
      - name: publish docker image
        run: |
          make push          